In [1]:
!pip install streamlit

Requirement already satisfied: streamlit in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.59.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (3.1.51)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (2.5.1)
Requirement already satisfied: packaging>=20 in C:\Users\shaguftha\AppData\Roaming\Python\Python314\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow<25,>=7.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\shaguftha\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette>=0.40.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools>=0.6.3 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (4.14.1)
Requirement already satisfied: python-multipart>=0.0.10 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (16.1)
Requirement already satisfied: itsdangerous>=2.1.2 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.24.0)
Requirement already satisfied: colorama in C:\Users\shaguftha\AppData\Roaming\Python\Python314\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\shaguftha\AppData\Roaming\Python\Python314\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in C:\Users\shaguftha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)

In [2]:
%%writefile app.py

import streamlit as st

st.title("My First Streamlit App")
st.write("Hello from  Shagufta!")

Writing app.py

In [3]:
!pip install requests

Requirement already satisfied: requests in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2026.6.17)

In [13]:
API_Key= "EFeiAVwmT8TLI0Qw2nv3eN4etZX83OQC2ma1fkcG"

In [14]:
import requests

In [15]:
import requests

api_key = "1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99"

url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&api_key={api_key}"

response = requests.get(url)

data = response.json()

print(data)

{'links': {'next': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-07&end_date=2024-01-13&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99', 'previous': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2023-12-26&end_date=2024-01-01&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99', 'self': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'element_count': 45, 'near_earth_objects': {'2024-01-02': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2415949', 'neo_reference_id': '2415949', 'name': '415949 (2001 XY10)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949', 'absolute_magnitude_h': 19.37, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883, 'estimated_diameter_max': 0.7944013596}, 'meters': {'estimated_diameter_min': 355.267088298, 'estimated_diameter_max': 794.4013596028}, 'miles': {'estimated_diameter_min': 0.2207526659, 'estimated_diameter_max': 0.4936179672}, 'feet': {'estimated_diameter_min': 1165.5744739718, 'estimated_diameter_max': 2606.3037566394}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:14', 'epoch_date_close_approach': 1704201240000, 'relative_velocity': {'kilometers_per_second': '15.8905264223', 'kilometers_per_hour': '57205.8951204341', 'miles_per_hour': '35545.5185541386'}, 'miss_distance': {'astronomical': '0.3372535274', 'lunar': '131.1916221586', 'kilometers': '50452409.349026638', 'miles': '31349673.4658100844'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3160747', 'neo_reference_id': '3160747', 'name': '(2003 SR84)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747', 'absolute_magnitude_h': 26.0, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462, 'estimated_diameter_max': 0.0375007522}, 'meters': {'estimated_diameter_min': 16.7708462163, 'estimated_diameter_max': 37.5007521798}, 'miles': {'estimated_diameter_min': 0.0104209175, 'estimated_diameter_max': 0.0233018799}, 'feet': {'estimated_diameter_min': 55.0224631002, 'estimated_diameter_max': 123.0339677816}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 22:45', 'epoch_date_close_approach': 1704235500000, 'relative_velocity': {'kilometers_per_second': '10.7191818981', 'kilometers_per_hour': '38589.054833182', 'miles_per_hour': '23977.7379878735'}, 'miss_distance': {'astronomical': '0.1323425924', 'lunar': '51.4812684436', 'kilometers': '19798169.933318188', 'miles': '12302012.3446714744'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3309828', 'neo_reference_id': '3309828', 'name': '(2005 YQ96)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828', 'absolute_magnitude_h': 20.62, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652, 'estimated_diameter_max': 0.4467247133}, 'meters': {'estimated_diameter_min': 199.78136523, 'estimated_diameter_max': 446.7247132921}, 'miles': {'estimated_diameter_min': 0.1241383467, 'estimated_diameter_max': 0.2775817818}, 'feet': {'estimated_diameter_min': 655.4506943013, 'estimated_diameter_max': 1465.6323083572}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 19:42', 'epoch_date_close_approach': 1704224520000, 'relative_velocity': {'kilometers_per_second': '15.6702817644', 'kilometers_per_hour': '56413.0143519451', 'miles_per_hour': '35052.8532788517'}, 'miss_distance': {'astronomical': '0.1670126223', 'lunar': '64.9679100747', 'kilometers': '24984732.559194501', 'miles': '15524792.9180700738'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3457842', 'neo_reference_id': '3457842', 'name': '(2009 HC21)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842', 'absolute_magnitude_h': 22.1, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415, 'estimated_diameter_max': 0.2259643771}, 'meters': {'estimated_diameter_min': 101.054341542, 'estimated_diameter_max': 225.9643771094}, 'miles': {'estimated_diameter_min': 0.0627922373, 'estimated_diameter_max': 0.140407711}, 'feet': {'estimated_diameter_min': 331.5431259047, 'estimated_diameter_max': 741.3529669956}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 12:06', 'epoch_date_close_approach': 1704197160000, 'relative_velocity': {'kilometers_per_second': '6.0808661718', 'kilometers_per_hour': '21891.1182185894', 'miles_per_hour': '13602.2895397674'}, 'miss_distance': {'astronomical': '0.4920511029', 'lunar': '191.4078790281', 'kilometers': '73609796.924990823', 'miles': '45739006.8632584374'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3553062', 'neo_reference_id': '3553062', 'name': '(2010 XA11)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062', 'absolute_magnitude_h': 26.1, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338, 'estimated_diameter_max': 0.0358129403}, 'meters': {'estimated_diameter_min': 16.0160337979, 'estimated_diameter_max': 35.8129403019}, 'miles': {'estimated_diameter_min': 0.0099518989, 'estimated_diameter_max': 0.0222531225}, 'feet': {'estimated_diameter_min': 52.5460443254, 'estimated_diameter_max': 117.4965270602}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 15:31', 'epoch_date_close_approach': 1704209460000, 'relative_velocity': {'kilometers_per_second': '8.7413828775', 'kilometers_per_hour': '31468.9783588978', 'miles_per_hour': '19553.5993586163'}, 'miss_distance': {'astronomical': '0.2358022486', 'lunar': '91.7270747054', 'kilometers': '35275514.131770482', 'miles': '21919188.0752253716'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3591616', 'neo_reference_id': '3591616', 'name': '(2011 YP10)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616', 'absolute_magnitude_h': 23.94, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885, 'estimated_diameter_max': 0.0968366995}, 'meters': {'estimated_diameter_min': 43.3066885476, 'estimated_diameter_max': 96.8366994728}, 'miles': {'estimated_diameter_min': 0.0269095204, 'estimated_diameter_max': 0.0601715168}, 'feet': {'estimated_diameter_min': 142.0823160544, 'estimated_diameter_max': 317.7057170982}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 12:59', 'epoch_date_close_approach': 1704200340000, 'relative_velocity': {'kilometers_per_second': '5.8070023218', 'kilometers_per_hour': '20905.2083584121', 'miles_per_hour': '12989.6834935922'}, 'miss_distance': {'astronomical': '0.0704899554', 'lunar': '27.4205926506', 'kilometers': '10545147.184234998', 'miles': '6552450.6191110524'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3608936', 'neo_reference_id': '3608936', 'name': '(2012 SD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936', 'absolute_magnitude_h': 20.05, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533, 'estimated_diameter_max': 0.580817882}, 'meters': {'estimated_diameter_min': 259.7496533301, 'estimated_diameter_max': 580.817881978}, 'miles': {'estimated_diameter_min': 0.1614009018, 'estimated_diameter_max': 0.3609033881}, 'feet': {'estimated_diameter_min': 852.1970526314, 'estimated_diameter_max': 1905.5705399087}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:50', 'epoch_date_close_approach': 1704203400000, 'relative_velocity': {'kilometers_per_second': '11.0227943004', 'kilometers_per_hour': '39682.059481597', 'miles_per_hour': '24656.8885706623'}, 'miss_distance': {'astronomical': '0.1644228854', 'lunar': '63.9605024206', 'kilometers': '24597313.435094098', 'miles': '15284061.8372026324'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3795154', 'neo_reference_id': '3795154', 'name': '(2017 YD8)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154', 'absolute_magnitude_h': 21.87, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177, 'estimated_diameter_max': 0.2512117673}, 'meters': {'estimated_diameter_min': 112.3453176718, 'estimated_diameter_max': 251.2117672679}, 'miles': {'estimated_diameter_min': 0.0698081224, 'estimated_diameter_max': 0.156095707}, 'feet': {'estimated_diameter_min': 368.5870120303, 'estimated_diameter_max': 824.1856145234}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 18:22', 'epoch_date_close_approach': 1704219720000, 'relative_velocity': {'kilometers_per_second': '18.9936426332', 'kilometers_per_hour': '68377.1134793652', 'miles_per_hour': '42486.8792061089'}, 'miss_distance': {'astronomical': '0.2012574006', 'lunar': '78.2891288334', 'kilometers': '30107678.451496722', 'miles': '18708043.8862378836'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3842680', 'neo_reference_id': '3842680', 'name': '(2019 KK5)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680', 'absolute_magnitude_h': 22.79, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089, 'estimated_diameter_max': 0.1644523102}, 'meters': {'estimated_diameter_min': 73.545308935, 'estimated_diameter_max': 164.452310205}, 'miles': {'estimated_diameter_min': 0.0456989222, 'estimated_diameter_max': 0.1021858964}, 'feet': {'estimated_diameter_min': 241.2903913664, 'estimated_diameter_max': 539.5417174129}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 21:21', 'epoch_date_close_approach': 1704230460000, 'relative_velocity': {'kilometers_per_second': '20.8331302779', 'kilometers_per_hour': '74999.2690004519', 'miles_per_hour': '46601.6291186419'}, 'miss_distance': {'astronomical': '0.0260972745', 'lunar': '10.1518397805', 'kilometers': '3904096.678005315', 'miles': '2425893.185550747'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2613286', 'neo_reference_id': '2613286', 'name': '613286 (2005 YQ96)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286', 'absolute_magnitude_h': 20.63, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532, 'estimated_diameter_max': 0.4446721997}, 'meters': {'estimated_diameter_min': 198.8634532359, 'estimated_diameter_max': 444.6721996757}, 'miles': {'estimated_diameter_min': 0.1235679828, 'estimated_diameter_max': 0.2763064094}, 'feet': {'estimated_diameter_min': 652.4391719144, 'estimated_diameter_max': 1458.8983395842}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 19:42', 'epoch_date_close_approach': 1704224520000, 'relative_velocity': {'kilometers_per_second': '15.6702896005', 'kilometers_per_hour': '56413.0425616862', 'miles_per_hour': '35052.8708072878'}, 'miss_distance': {'astronomical': '0.16701304', 'lunar': '64.96807256', 'kilometers': '24984795.0462248', 'miles': '15524831.74571024'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2669051', 'neo_reference_id': '2669051', 'name': '669051 (2012 SD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051', 'absolute_magnitude_h': 20.08, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545, 'estimated_diameter_max': 0.5728487619}, 'meters': {'estimated_diameter_min': 256.1857544793, 'estimated_diameter_max': 572.8487618827}, 'miles': {'estimated_diameter_min': 0.1591863984, 'estimated_diameter_max': 0.355951608}, 'feet': {'estimated_diameter_min': 840.5044707257, 'estimated_diameter_max': 1879.4251319352}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:50', 'epoch_date_close_approach': 1704203400000, 'relative_velocity': {'kilometers_per_second': '11.0227939149', 'kilometers_per_hour': '39682.0580935237', 'miles_per_hour': '24656.8877081676'}, 'miss_distance': {'astronomical': '0.1644228604', 'lunar': '63.9604926956', 'kilometers': '24597309.695147348', 'miles': '15284059.5133074824'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}], '2024-01-01': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3724393', 'neo_reference_id': '3724393', 'name': '(2015 OD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393', 'absolute_magnitude_h': 21.21, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185, 'estimated_diameter_max': 0.3404395273}, 'meters': {'estimated_diameter_min': 152.249185036, 'estimated_diameter_max': 340.4395272595}, 'miles': {'estimated_diameter_min': 0.0946032284, 'estimated_diameter_max': 0.2115392495}, 'feet': {'estimated_diameter_min': 499.5052162336, 'estimated_diameter_max': 1116.9276186141}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 11:58', 'epoch_date_close_approach': 1704110280000, 'relative_velocity': {'kilometers_per_second': '25.3931645932', 'kilometers_per_hour': '91415.3925356518', 'miles_per_hour': '56801.969878611'}, 'miss_distance': {'astronomical': '0.4372881787', 'lunar': '170.1051015143', 'kilometers': '65417380.109699369', 'miles': '40648475.1053305322'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3797695', 'neo_reference_id': '3797695', 'name': '(2018 BA)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695', 'absolute_magnitude_h': 25.0, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658, 'estimated_diameter_max': 0.0594346868}, 'meters': {'estimated_diameter_min': 26.58, 'estimated_diameter_max': 59.4346868419}, 'miles': {'estimated_diameter_min': 0.0165160412, 'estimated_diameter_max': 0.0369309908}, 'feet': {'estimated_diameter_min': 87.2047272, 'estimated_diameter_max': 194.9956979785}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 08:13', 'epoch_date_close_approach': 1704096780000, 'relative_velocity': {'kilometers_per_second': '16.7051869184', 'kilometers_per_hour': '60138.6729062958', 'miles_per_hour': '37367.8326178036'}, 'miss_distance': {'astronomical': '0.3961064439', 'lunar': '154.0854066771', 'kilometers': '59256680.300714493', 'miles': '36820393.7545182834'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3986699', 'neo_reference_id': '3986699', 'name': '(2020 BC)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699', 'absolute_magnitude_h': 26.2, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935, 'estimated_diameter_max': 0.0342010925}, 'meters': {'estimated_diameter_min': 15.2951935344, 'estimated_diameter_max': 34.201092472}, 'miles': {'estimated_diameter_min': 0.0095039897, 'estimated_diameter_max': 0.021251567}, 'feet': {'estimated_diameter_min': 50.1810827555, 'estimated_diameter_max': 112.2083122258}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 16:14', 'epoch_date_close_approach': 1704125640000, 'relative_velocity': {'kilometers_per_second': '8.3141771772', 'kilometers_per_hour': '29931.0378379052', 'miles_per_hour': '18597.9829276695'}, 'miss_distance': {'astronomical': '0.1675870266', 'lunar': '65.1913533474', 'kilometers': '25070662.218993342', 'miles': '15578187.1327464396'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}], '2024-01-04': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3541505?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3541505', 'neo_reference_id': '3541505', 'name': '(2010 PJ)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3541505', 'absolute_magnitude_h': 22.14, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0992098919, 'estimated_diameter_max': 0.2218400624}, 'meters': {'estimated_diameter_min': 99.2098919421, 'estimated_diameter_max': 221.8400624229}, 'miles': {'estimated_diameter_min': 0.0616461498, 'estimated_diameter_max': 0.1378449814}, 'feet': {'estimated_diameter_min': 325.4917818793, 'estimated_diameter_max': 727.8217503997}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-04', 'close_approach_date_full': '2024-Jan-04 13:32', 'epoch_date_close_approach': 1704375120000, 'relative_velocity': {'kilometers_per_second': '18.4122352237', 'kilometers_per_hour': '66284.046805343', 'miles_per_hour': '41186.3289719088'}, 'miss_distance': {'astronomical': '0.325882928', 'lunar': '126.768458992', 'kilometers': '48751391.89816336', 'miles': '30292710.233879968'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3759758?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3759758', 'neo_reference_id': '3759758', 'name': '(2016 SU2)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3759758', 'absolute_magnitude_h': 27.6, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0080270317, 'estimated_diameter_max': 0.0179489885}, 'meters': {'estimated_diameter_min': 8.0270316728, 'estimated_diameter_max': 17.948988478}, 'miles': {'estimated_diameter_min': 0.0049877647, 'estimated_diameter_max': 0.0111529809}, 'feet': {'estimated_diameter_min': 26.3354065935, 'estimated_diameter_max': 58.8877593581}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_dat

In [16]:
response = requests.get(url)

In [17]:
response

In [18]:
data.keys()

dict_keys(['links', 'element_count', 'near_earth_objects'])

In [19]:
data['links']

{'next': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-07&end_date=2024-01-13&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99',
 'previous': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2023-12-26&end_date=2024-01-01&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99',
 'self': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&detailed=false&api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}

In [20]:
data['near_earth_objects'].keys()

dict_keys(['2024-01-02', '2024-01-01', '2024-01-04', '2024-01-03', '2024-01-06', '2024-01-05', '2024-01-07'])

In [21]:
data['element_count']

45

In [22]:
details = data['near_earth_objects']
details

{'2024-01-02': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '2415949',
   'neo_reference_id': '2415949',
   'name': '415949 (2001 XY10)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
   'absolute_magnitude_h': 19.37,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
     'estimated_diameter_max': 0.7944013596},
    'meters': {'estimated_diameter_min': 355.267088298,
     'estimated_diameter_max': 794.4013596028},
    'miles': {'estimated_diameter_min': 0.2207526659,
     'estimated_diameter_max': 0.4936179672},
    'feet': {'estimated_diameter_min': 1165.5744739718,
     'estimated_diameter_max': 2606.3037566394}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:14',
     'epoch_date_close_approach': 1704201240000,
     'relative_velocity': {'kilometers_per_second': '15.8905264223',
      'kilometers_per_hour': '57205.8951204341',
      'miles_per_hour': '35545.5185541386'},
     'miss_distance': {'astronomical': '0.3372535274',
      'lunar': '131.1916221586',
      'kilometers': '50452409.349026638',
      'miles': '31349673.4658100844'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3160747',
   'neo_reference_id': '3160747',
   'name': '(2003 SR84)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
   'absolute_magnitude_h': 26.0,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
     'estimated_diameter_max': 0.0375007522},
    'meters': {'estimated_diameter_min': 16.7708462163,
     'estimated_diameter_max': 37.5007521798},
    'miles': {'estimated_diameter_min': 0.0104209175,
     'estimated_diameter_max': 0.0233018799},
    'feet': {'estimated_diameter_min': 55.0224631002,
     'estimated_diameter_max': 123.0339677816}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 22:45',
     'epoch_date_close_approach': 1704235500000,
     'relative_velocity': {'kilometers_per_second': '10.7191818981',
      'kilometers_per_hour': '38589.054833182',
      'miles_per_hour': '23977.7379878735'},
     'miss_distance': {'astronomical': '0.1323425924',
      'lunar': '51.4812684436',
      'kilometers': '19798169.933318188',
      'miles': '12302012.3446714744'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3309828',
   'neo_reference_id': '3309828',
   'name': '(2005 YQ96)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828',
   'absolute_magnitude_h': 20.62,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652,
     'estimated_diameter_max': 0.4467247133},
    'meters': {'estimated_diameter_min': 199.78136523,
     'estimated_diameter_max': 446.7247132921},
    'miles': {'estimated_diameter_min': 0.1241383467,
     'estimated_diameter_max': 0.2775817818},
    'feet': {'estimated_diameter_min': 655.4506943013,
     'estimated_diameter_max': 1465.6323083572}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 19:42',
     'epoch_date_close_approach': 1704224520000,
     'relative_velocity': {'kilometers_per_second': '15.6702817644',
      'kilometers_per_hour': '56413.0143519451',
      'miles_per_hour': '35052.8532788517'},
     'miss_distance': {'astronomical': '0.1670126223',
      'lunar': '64.9679100747',
      'kilometers': '24984732.559194501',
      'miles': '15524792.9180700738'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3457842',
   'neo_reference_id': '3457842',
   'name': '(2009 HC21)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842',
   'absolute_magnitude_h': 22.1,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415,
     'estimated_diameter_max': 0.2259643771},
    'meters': {'estimated_diameter_min': 101.054341542,
     'estimated_diameter_max': 225.9643771094},
    'miles': {'estimated_diameter_min': 0.0627922373,
     'estimated_diameter_max': 0.140407711},
    'feet': {'estimated_diameter_min': 331.5431259047,
     'estimated_diameter_max': 741.3529669956}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 12:06',
     'epoch_date_close_approach': 1704197160000,
     'relative_velocity': {'kilometers_per_second': '6.0808661718',
      'kilometers_per_hour': '21891.1182185894',
      'miles_per_hour': '13602.2895397674'},
     'miss_distance': {'astronomical': '0.4920511029',
      'lunar': '191.4078790281',
      'kilometers': '73609796.924990823',
      'miles': '45739006.8632584374'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3553062',
   'neo_reference_id': '3553062',
   'name': '(2010 XA11)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062',
   'absolute_magnitude_h': 26.1,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
     'estimated_diameter_max': 0.0358129403},
    'meters': {'estimated_diameter_min': 16.0160337979,
     'estimated_diameter_max': 35.8129403019},
    'miles': {'estimated_diameter_min': 0.0099518989,
     'estimated_diameter_max': 0.0222531225},
    'feet': {'estimated_diameter_min': 52.5460443254,
     'estimated_diameter_max': 117.4965270602}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 15:31',
     'epoch_date_close_approach': 1704209460000,
     'relative_velocity': {'kilometers_per_second': '8.7413828775',
      'kilometers_per_hour': '31468.9783588978',
      'miles_per_hour': '19553.5993586163'},
     'miss_distance': {'astronomical': '0.2358022486',
      'lunar': '91.7270747054',
      'kilometers': '35275514.131770482',
      'miles': '21919188.0752253716'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3591616',
   'neo_reference_id': '3591616',
   'name': '(2011 YP10)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616',
   'absolute_magnitude_h': 23.94,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885,
     'estimated_diameter_max': 0.0968366995},
    'meters': {'estimated_diameter_min': 43.3066885476,
     'estimated_diameter_max': 96.8366994728},
    'miles': {'estimated_diameter_min': 0.0269095204,
     'estimated_diameter_max': 0.0601715168},
    'feet': {'estimated_diameter_min': 142.0823160544,
     'estimated_diameter_max': 317.7057170982}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 12:59',
     'epoch_date_close_approach': 1704200340000,
     'relative_velocity': {'kilometers_per_second': '5.8070023218',
      'kilometers_per_hour': '20905.2083584121',
      'miles_per_hour': '12989.6834935922'},
     'miss_distance': {'astronomical': '0.0704899554',
      'lunar': '27.4205926506',
      'kilometers': '10545147.184234998',
      'miles': '6552450.6191110524'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3608936',
   'neo_reference_id': '3608936',
   'name': '(2012 SD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936',
   'absolute_magnitude_h': 20.05,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533,
     'estimated_diameter_max': 0.580817882},
    'meters': {'estimated_diameter_min': 259.7496533301,
     'estimated_diameter_max': 580.817881978},
    'miles': {'estimated_diameter_min': 0.1614009018,
     'estimated_diameter_max': 0.3609033881},
    'feet': {'estimated_diameter_min': 852.1970526314,
     'estimated_diameter_max': 1905.5705399087}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:50',
     'epoch_date_close_approach': 1704203400000,
     'relative_velocity': {'kilometers_per_second': '11.0227943004',
      'kilometers_per_hour': '39682.059481597',
      'miles_per_hour': '24656.8885706623'},
     'miss_distance': {'astronomical': '0.1644228854',
      'lunar': '63.9605024206',
      'kilometers': '24597313.435094098',
      'miles': '15284061.8372026324'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3795154',
   'neo_reference_id': '3795154',
   'name': '(2017 YD8)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154',
   'absolute_magnitude_h': 21.87,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177,
     'estimated_diameter_max': 0.2512117673},
    'meters': {'estimated_diameter_min': 112.3453176718,
     'estimated_diameter_max': 251.2117672679},
    'miles': {'estimated_diameter_min': 0.0698081224,
     'estimated_diameter_max': 0.156095707},
    'feet': {'estimated_diameter_min': 368.5870120303,
     'estimated_diameter_max': 824.1856145234}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 18:22',
     'epoch_date_close_approach': 1704219720000,
     'relative_velocity': {'kilometers_per_second': '18.9936426332',
      'kilometers_per_hour': '68377.1134793652',
      'miles_per_hour': '42486.8792061089'},
     'miss_distance': {'astronomical': '0.2012574006',
      'lunar': '78.2891288334',
      'kilometers': '30107678.451496722',
      'miles': '18708043.8862378836'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3842680',
   'neo_reference_id': '3842680',
   'name': '(2019 KK5)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680',
   'absolute_magnitude_h': 22.79,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089,
     'estimated_diameter_max': 0.1644523102},
    'meters': {'estimated_diameter_min': 73.545308935,
     'estimated_diameter_max': 164.452310205},
    'miles': {'estimated_diameter_min': 0.0456989222,
     'estimated_diameter_max': 0.1021858964},
    'feet': {'estimated_diameter_min': 241.2903913664,
     'estimated_diameter_max': 539.5417174129}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 21:21',
     'epoch_date_close_approach': 1704230460000,
     'relative_velocity': {'kilometers_per_second': '20.8331302779',
      'kilometers_per_hour': '74999.2690004519',
      'miles_per_hour': '46601.6291186419'},
     'miss_distance': {'astronomical': '0.0260972745',
      'lunar': '10.1518397805',
      'kilometers': '3904096.678005315',
      'miles': '2425893.185550747'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '2613286',
   'neo_reference_id': '2613286',
   'name': '613286 (2005 YQ96)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286',
   'absolute_magnitude_h': 20.63,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532,
     'estimated_diameter_max': 0.4446721997},
    'meters': {'estimated_diameter_min': 198.8634532359,
     'estimated_diameter_max': 444.6721996757},
    'miles': {'estimated_diameter_min': 0.1235679828,
     'estimated_diameter_max': 0.2763064094},
    'feet': {'estimated_diameter_min': 652.4391719144,
     'estimated_diameter_max': 1458.8983395842}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 19:42',
     'epoch_date_close_approach': 1704224520000,
     'relative_velocity': {'kilometers_per_second': '15.6702896005',
      'kilometers_per_hour': '56413.0425616862',
      'miles_per_hour': '35052.8708072878'},
     'miss_distance': {'astronomical': '0.16701304',
      'lunar': '64.96807256',
      'kilometers': '24984795.0462248',
      'miles': '15524831.74571024'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '2669051',
   'neo_reference_id': '2669051',
   'name': '669051 (2012 SD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051',
   'absolute_magnitude_h': 20.08,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545,
     'estimated_diameter_max': 0.5728487619},
    'meters': {'estimated_diameter_min': 256.1857544793,
     'estimated_diameter_max': 572.8487618827},
    'miles': {'estimated_diameter_min': 0.1591863984,
     'estimated_diameter_max': 0.355951608},
    'feet': {'estimated_diameter_min': 840.5044707257,
     'estimated_diameter_max': 1879.4251319352}},
   'is_potentially_hazardous_asteroid': True,
   'close_approach_data': [{'close_approach_date': '2024-01-02',
     'close_approach_date_full': '2024-Jan-02 13:50',
     'epoch_date_close_approach': 1704203400000,
     'relative_velocity': {'kilometers_per_second': '11.0227939149',
      'kilometers_per_hour': '39682.0580935237',
      'miles_per_hour': '24656.8877081676'},
     'miss_distance': {'astronomical': '0.1644228604',
      'lunar': '63.9604926956',
      'kilometers': '24597309.695147348',
      'miles': '15284059.5133074824'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False}],
 '2024-01-01': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3724393',
   'neo_reference_id': '3724393',
   'name': '(2015 OD22)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393',
   'absolute_magnitude_h': 21.21,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185,
     'estimated_diameter_max': 0.3404395273},
    'meters': {'estimated_diameter_min': 152.249185036,
     'estimated_diameter_max': 340.4395272595},
    'miles': {'estimated_diameter_min': 0.0946032284,
     'estimated_diameter_max': 0.2115392495},
    'feet': {'estimated_diameter_min': 499.5052162336,
     'estimated_diameter_max': 1116.9276186141}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 11:58',
     'epoch_date_close_approach': 1704110280000,
     'relative_velocity': {'kilometers_per_second': '25.3931645932',
      'kilometers_per_hour': '91415.3925356518',
      'miles_per_hour': '56801.969878611'},
     'miss_distance': {'astronomical': '0.4372881787',
      'lunar': '170.1051015143',
      'kilometers': '65417380.109699369',
      'miles': '40648475.1053305322'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3797695',
   'neo_reference_id': '3797695',
   'name': '(2018 BA)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695',
   'absolute_magnitude_h': 25.0,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658,
     'estimated_diameter_max': 0.0594346868},
    'meters': {'estimated_diameter_min': 26.58,
     'estimated_diameter_max': 59.4346868419},
    'miles': {'estimated_diameter_min': 0.0165160412,
     'estimated_diameter_max': 0.0369309908},
    'feet': {'estimated_diameter_min': 87.2047272,
     'estimated_diameter_max': 194.9956979785}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 08:13',
     'epoch_date_close_approach': 1704096780000,
     'relative_velocity': {'kilometers_per_second': '16.7051869184',
      'kilometers_per_hour': '60138.6729062958',
      'miles_per_hour': '37367.8326178036'},
     'miss_distance': {'astronomical': '0.3961064439',
      'lunar': '154.0854066771',
      'kilometers': '59256680.300714493',
      'miles': '36820393.7545182834'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False},
  {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3986699',
   'neo_reference_id': '3986699',
   'name': '(2020 BC)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699',
   'absolute_magnitude_h': 26.2,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935,
     'estimated_diameter_max': 0.0342010925},
    'meters': {'estimated_diameter_min': 15.2951935344,
     'estimated_diameter_max': 34.201092472},
    'miles': {'estimated_diameter_min': 0.0095039897,
     'estimated_diameter_max': 0.021251567},
    'feet': {'estimated_diameter_min': 50.1810827555,
     'estimated_diameter_max': 112.2083122258}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-01',
     'close_approach_date_full': '2024-Jan-01 16:14',
     'epoch_date_close_approach': 1704125640000,
     'relative_velocity': {'kilometers_per_second': '8.3141771772',
      'kilometers_per_hour': '29931.0378379052',
      'miles_per_hour': '18597.9829276695'},
     'miss_distance': {'astronomical': '0.1675870266',
      'lunar': '65.1913533474',
      'kilometers': '25070662.218993342',
      'miles': '15578187.1327464396'},
     'orbiting_body': 'Earth'}],
   'is_sentry_object': False}],
 '2024-01-04': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3541505?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'},
   'id': '3541505',
   'neo_reference_id': '3541505',
   'name': '(2010 PJ)',
   'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3541505',
   'absolute_magnitude_h': 22.14,
   'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0992098919,
     'estimated_diameter_max': 0.2218400624},
    'meters': {'estimated_diameter_min': 99.2098919421,
     'estimated_diameter_max': 221.8400624229},
    'miles': {'estimated_diameter_min': 0.0616461498,
     'estimated_diameter_max': 0.1378449814},
    'feet': {'estimated_diameter_min': 325.4917818793,
     'estimated_diameter_max': 727.8217503997}},
   'is_potentially_hazardous_asteroid': False,
   'close_approach_data': [{'close_approach_date': '2024-01-04',
     'close_approach_date_full': '2024-Jan-04 13:32',

In [23]:
for date, asteroids in details.items():
    print(f"Date: {date}")
    for asteroid in asteroids:
        name = asteroid['name']
        diameter = asteroid['estimated_diameter']['meters']['estimated_diameter_max']
        is_hazardous = asteroid['is_potentially_hazardous_asteroid']
        print(f"Asteroid Name: {name}, Diameter: {diameter} meters, Potentially Hazardous: {is_hazardous}")

Date: 2024-01-02
Asteroid Name: 415949 (2001 XY10), Diameter: 794.4013596028 meters, Potentially Hazardous: False
Asteroid Name: (2003 SR84), Diameter: 37.5007521798 meters, Potentially Hazardous: False
Asteroid Name: (2005 YQ96), Diameter: 446.7247132921 meters, Potentially Hazardous: True
Asteroid Name: (2009 HC21), Diameter: 225.9643771094 meters, Potentially Hazardous: False
Asteroid Name: (2010 XA11), Diameter: 35.8129403019 meters, Potentially Hazardous: False
Asteroid Name: (2011 YP10), Diameter: 96.8366994728 meters, Potentially Hazardous: False
Asteroid Name: (2012 SD22), Diameter: 580.817881978 meters, Potentially Hazardous: True
Asteroid Name: (2017 YD8), Diameter: 251.2117672679 meters, Potentially Hazardous: False
Asteroid Name: (2019 KK5), Diameter: 164.452310205 meters, Potentially Hazardous: False
Asteroid Name: 613286 (2005 YQ96), Diameter: 444.6721996757 meters, Potentially Hazardous: True
Asteroid Name: 669051 (2012 SD22), Diameter: 572.8487618827 meters, Potentially Hazardous: True
Date: 2024-01-01
Asteroid Name: (2015 OD22), Diameter: 340.4395272595 meters, Potentially Hazardous: False
Asteroid Name: (2018 BA), Diameter: 59.4346868419 meters, Potentially Hazardous: False
Asteroid Name: (2020 BC), Diameter: 34.201092472 meters, Potentially Hazardous: False
Date: 2024-01-04
Asteroid Name: (2010 PJ), Diameter: 221.8400624229 meters, Potentially Hazardous: False
Asteroid Name: (2016 SU2), Diameter: 17.948988478 meters, Potentially Hazardous: False
Date: 2024-01-03
Asteroid Name: (2003 JV14), Diameter: 313.3574170739 meters, Potentially Hazardous: False
Asteroid Name: (2011 YE40), Diameter: 54.2050786336 meters, Potentially Hazardous: False
Asteroid Name: (2012 AB11), Diameter: 204.1925904549 meters, Potentially Hazardous: False
Asteroid Name: (2012 LJ2), Diameter: 271.6689340891 meters, Potentially Hazardous: False
Asteroid Name: (2013 NT11), Diameter: 751.6920874957 meters, Potentially Hazardous: False
Asteroid Name: (2016 GZ215), Diameter: 361.4431335863 meters, Potentially Hazardous: False
Asteroid Name: (2017 UJ2), Diameter: 3.9268108181 meters, Potentially Hazardous: False
Asteroid Name: (2017 WQ1), Diameter: 59.9846292283 meters, Potentially Hazardous: False
Asteroid Name: (2019 AE3), Diameter: 19.6806745089 meters, Potentially Hazardous: False
Asteroid Name: (2020 BG1), Diameter: 228.0551997482 meters, Potentially Hazardous: False
Asteroid Name: 668499 (2012 AB11), Diameter: 204.1925904549 meters, Potentially Hazardous: False
Date: 2024-01-06
Asteroid Name: 304640 (2006 WW1), Diameter: 871.043769791 meters, Potentially Hazardous: False
Asteroid Name: (2002 AO11), Diameter: 145.8948556919 meters, Potentially Hazardous: False
Asteroid Name: (2013 AK20), Diameter: 136.7854737026 meters, Potentially Hazardous: False
Asteroid Name: (2013 EU9), Diameter: 276.719636665 meters, Potentially Hazardous: False
Asteroid Name: (2016 JX5), Diameter: 24.7765012606 meters, Potentially Hazardous: False
Asteroid Name: (2017 PM26), Diameter: 329.6400556414 meters, Potentially Hazardous: False
Asteroid Name: (2017 YZ1), Diameter: 487.5733713755 meters, Potentially Hazardous: True
Asteroid Name: 591179 (2013 EU9), Diameter: 276.719636665 meters, Potentially Hazardous: False
Date: 2024-01-05
Asteroid Name: (2007 SG11), Diameter: 172.9975603978 meters, Potentially Hazardous: False
Asteroid Name: (2013 YD), Diameter: 113.2504610618 meters, Potentially Hazardous: False
Asteroid Name: (2016 RW19), Diameter: 380.2243960879 meters, Potentially Hazardous: False
Asteroid Name: (2017 YA8), Diameter: 203.2544107219 meters, Potentially Hazardous: False
Asteroid Name: (2020 BT8), Diameter: 174.5982871157 meters, Potentially Hazardous: False
Date: 2024-01-07
Asteroid Name: 199003 (2005 WJ56), Diameter: 1386.8834919048 meters, Potentially Hazardous: True
Asteroid Name: (2007 YZ), Diameter: 737.9721606833 meters, Potentially Hazardous: False
Asteroid Name: (2010 JR34), Diameter: 17.1411509231 meters, Potentially Hazardous: False
Asteroid Name: (2012 BV13), Diameter: 207.0331923453 meters, Potentially Hazardous: False
Asteroid Name: (2019 PJ), Diameter: 104.2413383852 meters, Potentially Hazardous: False

In [24]:
for date, asteroids in details.items():
    print(date, asteroids)

2024-01-02 [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2415949', 'neo_reference_id': '2415949', 'name': '415949 (2001 XY10)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949', 'absolute_magnitude_h': 19.37, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883, 'estimated_diameter_max': 0.7944013596}, 'meters': {'estimated_diameter_min': 355.267088298, 'estimated_diameter_max': 794.4013596028}, 'miles': {'estimated_diameter_min': 0.2207526659, 'estimated_diameter_max': 0.4936179672}, 'feet': {'estimated_diameter_min': 1165.5744739718, 'estimated_diameter_max': 2606.3037566394}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:14', 'epoch_date_close_approach': 1704201240000, 'relative_velocity': {'kilometers_per_second': '15.8905264223', 'kilometers_per_hour': '57205.8951204341', 'miles_per_hour': '35545.5185541386'}, 'miss_distance': {'astronomical': '0.3372535274', 'lunar': '131.1916221586', 'kilometers': '50452409.349026638', 'miles': '31349673.4658100844'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3160747', 'neo_reference_id': '3160747', 'name': '(2003 SR84)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747', 'absolute_magnitude_h': 26.0, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462, 'estimated_diameter_max': 0.0375007522}, 'meters': {'estimated_diameter_min': 16.7708462163, 'estimated_diameter_max': 37.5007521798}, 'miles': {'estimated_diameter_min': 0.0104209175, 'estimated_diameter_max': 0.0233018799}, 'feet': {'estimated_diameter_min': 55.0224631002, 'estimated_diameter_max': 123.0339677816}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 22:45', 'epoch_date_close_approach': 1704235500000, 'relative_velocity': {'kilometers_per_second': '10.7191818981', 'kilometers_per_hour': '38589.054833182', 'miles_per_hour': '23977.7379878735'}, 'miss_distance': {'astronomical': '0.1323425924', 'lunar': '51.4812684436', 'kilometers': '19798169.933318188', 'miles': '12302012.3446714744'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3309828', 'neo_reference_id': '3309828', 'name': '(2005 YQ96)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828', 'absolute_magnitude_h': 20.62, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652, 'estimated_diameter_max': 0.4467247133}, 'meters': {'estimated_diameter_min': 199.78136523, 'estimated_diameter_max': 446.7247132921}, 'miles': {'estimated_diameter_min': 0.1241383467, 'estimated_diameter_max': 0.2775817818}, 'feet': {'estimated_diameter_min': 655.4506943013, 'estimated_diameter_max': 1465.6323083572}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 19:42', 'epoch_date_close_approach': 1704224520000, 'relative_velocity': {'kilometers_per_second': '15.6702817644', 'kilometers_per_hour': '56413.0143519451', 'miles_per_hour': '35052.8532788517'}, 'miss_distance': {'astronomical': '0.1670126223', 'lunar': '64.9679100747', 'kilometers': '24984732.559194501', 'miles': '15524792.9180700738'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3457842', 'neo_reference_id': '3457842', 'name': '(2009 HC21)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842', 'absolute_magnitude_h': 22.1, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415, 'estimated_diameter_max': 0.2259643771}, 'meters': {'estimated_diameter_min': 101.054341542, 'estimated_diameter_max': 225.9643771094}, 'miles': {'estimated_diameter_min': 0.0627922373, 'estimated_diameter_max': 0.140407711}, 'feet': {'estimated_diameter_min': 331.5431259047, 'estimated_diameter_max': 741.3529669956}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 12:06', 'epoch_date_close_approach': 1704197160000, 'relative_velocity': {'kilometers_per_second': '6.0808661718', 'kilometers_per_hour': '21891.1182185894', 'miles_per_hour': '13602.2895397674'}, 'miss_distance': {'astronomical': '0.4920511029', 'lunar': '191.4078790281', 'kilometers': '73609796.924990823', 'miles': '45739006.8632584374'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3553062', 'neo_reference_id': '3553062', 'name': '(2010 XA11)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062', 'absolute_magnitude_h': 26.1, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338, 'estimated_diameter_max': 0.0358129403}, 'meters': {'estimated_diameter_min': 16.0160337979, 'estimated_diameter_max': 35.8129403019}, 'miles': {'estimated_diameter_min': 0.0099518989, 'estimated_diameter_max': 0.0222531225}, 'feet': {'estimated_diameter_min': 52.5460443254, 'estimated_diameter_max': 117.4965270602}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 15:31', 'epoch_date_close_approach': 1704209460000, 'relative_velocity': {'kilometers_per_second': '8.7413828775', 'kilometers_per_hour': '31468.9783588978', 'miles_per_hour': '19553.5993586163'}, 'miss_distance': {'astronomical': '0.2358022486', 'lunar': '91.7270747054', 'kilometers': '35275514.131770482', 'miles': '21919188.0752253716'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3591616', 'neo_reference_id': '3591616', 'name': '(2011 YP10)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616', 'absolute_magnitude_h': 23.94, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885, 'estimated_diameter_max': 0.0968366995}, 'meters': {'estimated_diameter_min': 43.3066885476, 'estimated_diameter_max': 96.8366994728}, 'miles': {'estimated_diameter_min': 0.0269095204, 'estimated_diameter_max': 0.0601715168}, 'feet': {'estimated_diameter_min': 142.0823160544, 'estimated_diameter_max': 317.7057170982}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 12:59', 'epoch_date_close_approach': 1704200340000, 'relative_velocity': {'kilometers_per_second': '5.8070023218', 'kilometers_per_hour': '20905.2083584121', 'miles_per_hour': '12989.6834935922'}, 'miss_distance': {'astronomical': '0.0704899554', 'lunar': '27.4205926506', 'kilometers': '10545147.184234998', 'miles': '6552450.6191110524'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3608936', 'neo_reference_id': '3608936', 'name': '(2012 SD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936', 'absolute_magnitude_h': 20.05, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533, 'estimated_diameter_max': 0.580817882}, 'meters': {'estimated_diameter_min': 259.7496533301, 'estimated_diameter_max': 580.817881978}, 'miles': {'estimated_diameter_min': 0.1614009018, 'estimated_diameter_max': 0.3609033881}, 'feet': {'estimated_diameter_min': 852.1970526314, 'estimated_diameter_max': 1905.5705399087}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:50', 'epoch_date_close_approach': 1704203400000, 'relative_velocity': {'kilometers_per_second': '11.0227943004', 'kilometers_per_hour': '39682.059481597', 'miles_per_hour': '24656.8885706623'}, 'miss_distance': {'astronomical': '0.1644228854', 'lunar': '63.9605024206', 'kilometers': '24597313.435094098', 'miles': '15284061.8372026324'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3795154', 'neo_reference_id': '3795154', 'name': '(2017 YD8)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154', 'absolute_magnitude_h': 21.87, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177, 'estimated_diameter_max': 0.2512117673}, 'meters': {'estimated_diameter_min': 112.3453176718, 'estimated_diameter_max': 251.2117672679}, 'miles': {'estimated_diameter_min': 0.0698081224, 'estimated_diameter_max': 0.156095707}, 'feet': {'estimated_diameter_min': 368.5870120303, 'estimated_diameter_max': 824.1856145234}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 18:22', 'epoch_date_close_approach': 1704219720000, 'relative_velocity': {'kilometers_per_second': '18.9936426332', 'kilometers_per_hour': '68377.1134793652', 'miles_per_hour': '42486.8792061089'}, 'miss_distance': {'astronomical': '0.2012574006', 'lunar': '78.2891288334', 'kilometers': '30107678.451496722', 'miles': '18708043.8862378836'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3842680', 'neo_reference_id': '3842680', 'name': '(2019 KK5)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680', 'absolute_magnitude_h': 22.79, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089, 'estimated_diameter_max': 0.1644523102}, 'meters': {'estimated_diameter_min': 73.545308935, 'estimated_diameter_max': 164.452310205}, 'miles': {'estimated_diameter_min': 0.0456989222, 'estimated_diameter_max': 0.1021858964}, 'feet': {'estimated_diameter_min': 241.2903913664, 'estimated_diameter_max': 539.5417174129}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 21:21', 'epoch_date_close_approach': 1704230460000, 'relative_velocity': {'kilometers_per_second': '20.8331302779', 'kilometers_per_hour': '74999.2690004519', 'miles_per_hour': '46601.6291186419'}, 'miss_distance': {'astronomical': '0.0260972745', 'lunar': '10.1518397805', 'kilometers': '3904096.678005315', 'miles': '2425893.185550747'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2613286', 'neo_reference_id': '2613286', 'name': '613286 (2005 YQ96)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286', 'absolute_magnitude_h': 20.63, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532, 'estimated_diameter_max': 0.4446721997}, 'meters': {'estimated_diameter_min': 198.8634532359, 'estimated_diameter_max': 444.6721996757}, 'miles': {'estimated_diameter_min': 0.1235679828, 'estimated_diameter_max': 0.2763064094}, 'feet': {'estimated_diameter_min': 652.4391719144, 'estimated_diameter_max': 1458.8983395842}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 19:42', 'epoch_date_close_approach': 1704224520000, 'relative_velocity': {'kilometers_per_second': '15.6702896005', 'kilometers_per_hour': '56413.0425616862', 'miles_per_hour': '35052.8708072878'}, 'miss_distance': {'astronomical': '0.16701304', 'lunar': '64.96807256', 'kilometers': '24984795.0462248', 'miles': '15524831.74571024'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '2669051', 'neo_reference_id': '2669051', 'name': '669051 (2012 SD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051', 'absolute_magnitude_h': 20.08, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545, 'estimated_diameter_max': 0.5728487619}, 'meters': {'estimated_diameter_min': 256.1857544793, 'estimated_diameter_max': 572.8487618827}, 'miles': {'estimated_diameter_min': 0.1591863984, 'estimated_diameter_max': 0.355951608}, 'feet': {'estimated_diameter_min': 840.5044707257, 'estimated_diameter_max': 1879.4251319352}}, 'is_potentially_hazardous_asteroid': True, 'close_approach_data': [{'close_approach_date': '2024-01-02', 'close_approach_date_full': '2024-Jan-02 13:50', 'epoch_date_close_approach': 1704203400000, 'relative_velocity': {'kilometers_per_second': '11.0227939149', 'kilometers_per_hour': '39682.0580935237', 'miles_per_hour': '24656.8877081676'}, 'miss_distance': {'astronomical': '0.1644228604', 'lunar': '63.9604926956', 'kilometers': '24597309.695147348', 'miles': '15284059.5133074824'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}]
2024-01-01 [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3724393', 'neo_reference_id': '3724393', 'name': '(2015 OD22)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393', 'absolute_magnitude_h': 21.21, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185, 'estimated_diameter_max': 0.3404395273}, 'meters': {'estimated_diameter_min': 152.249185036, 'estimated_diameter_max': 340.4395272595}, 'miles': {'estimated_diameter_min': 0.0946032284, 'estimated_diameter_max': 0.2115392495}, 'feet': {'estimated_diameter_min': 499.5052162336, 'estimated_diameter_max': 1116.9276186141}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 11:58', 'epoch_date_close_approach': 1704110280000, 'relative_velocity': {'kilometers_per_second': '25.3931645932', 'kilometers_per_hour': '91415.3925356518', 'miles_per_hour': '56801.969878611'}, 'miss_distance': {'astronomical': '0.4372881787', 'lunar': '170.1051015143', 'kilometers': '65417380.109699369', 'miles': '40648475.1053305322'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3797695', 'neo_reference_id': '3797695', 'name': '(2018 BA)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695', 'absolute_magnitude_h': 25.0, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658, 'estimated_diameter_max': 0.0594346868}, 'meters': {'estimated_diameter_min': 26.58, 'estimated_diameter_max': 59.4346868419}, 'miles': {'estimated_diameter_min': 0.0165160412, 'estimated_diameter_max': 0.0369309908}, 'feet': {'estimated_diameter_min': 87.2047272, 'estimated_diameter_max': 194.9956979785}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 08:13', 'epoch_date_close_approach': 1704096780000, 'relative_velocity': {'kilometers_per_second': '16.7051869184', 'kilometers_per_hour': '60138.6729062958', 'miles_per_hour': '37367.8326178036'}, 'miss_distance': {'astronomical': '0.3961064439', 'lunar': '154.0854066771', 'kilometers': '59256680.300714493', 'miles': '36820393.7545182834'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}, {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=1d5ou0T5XEHLHSu20peDJOkBAkYNXmjWq5U5uU99'}, 'id': '3986699', 'neo_reference_id': '3986699', 'name': '(2020 BC)', 'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699', 'absolute_magnitude_h': 26.2, 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935, 'estimated_diameter_max': 0.0342010925}, 'meters': {'estimated_diameter_min': 15.2951935344, 'estimated_diameter_max': 34.201092472}, 'miles': {'estimated_diameter_min': 0.0095039897, 'estimated_diameter_max': 0.021251567}, 'feet': {'estimated_diameter_min': 50.1810827555, 'estimated_diameter_max': 112.2083122258}}, 'is_potentially_hazardous_asteroid': False, 'close_approach_data': [{'close_approach_date': '2024-01-01', 'close_approach_date_full': '2024-Jan-01 16:14', 'epoch_date_close_approach': 1704125640000, 'relative_velocity': {'kilometers_per_second': '8.3141771772', 'kilometers_per_hour': '29931.0378379052', 'miles_per_hour': '18597.9829276695'}, 'miss_distance': {'astronomical': '0.1675870266', 'lunar': '65.1913533474', 'kilometers': '25070662.218993342', 'miles': '15578187.1327464396'}, 'orbiting_body': 'Earth'}], 'is_sentry_object': False}]

In [25]:
details.items

In [26]:
details['2024-01-02'][0]['estimated_diameter']['kilometers']['estimated_diameter_max']

0.7944013596

In [27]:
details['2024-01-02'][1]['estimated_diameter']['kilometers']['estimated_diameter_max']

0.0375007522

In [28]:
asteroid_data = []
target_date = 1000
API_Key= "EFeiAVwmT8TLI0Qw2nv3eN4etZX83OQC2ma1fkcG"
url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-07&api_key={API_Key}"

while(len(asteroid_data) < target_date):
    response = requests.get(url)
    data = response.json()
    near_earth_objects = data['near_earth_objects']
    
    for date, asteroids in near_earth_objects.items():
        for asteroid in asteroids:
            asteroid_data.append(
                dict (
                    id = int(asteroid['id']),
                    neo_reference_id = int(asteroid['neo_reference_id']),
                    name = asteroid['name'],
                    absolute_magnitude_h = float(asteroid['absolute_magnitude_h']),
                    estimated_diameter_min = float(asteroid['estimated_diameter']['meters']['estimated_diameter_min']),
                    estimated_diameter_max = float(asteroid['estimated_diameter']['meters']['estimated_diameter_max']),
                    is_potentially_hazardous_asteroid = bool(asteroid['is_potentially_hazardous_asteroid']),
                    close_approach_date = asteroid['close_approach_data'][0]['close_approach_date'],
                    relative_velocity_km_per_sec = float(asteroid['close_approach_data'][0]['relative_velocity']['kilometers_per_second']),
                    astronomical = float(asteroid['close_approach_data'][0]['miss_distance']['astronomical']),
                    miss_distance_km = float(asteroid['close_approach_data'][0]['miss_distance']['kilometers']),
                    miss_distance_lunar = float(asteroid['close_approach_data'][0]['miss_distance']['lunar']),
                    orbiting_body = asteroid['close_approach_data'][0]['orbiting_body']
            ) )
            if len(asteroid_data) >= target_date:
                          break

        if len(asteroid_data) >= target_date:
                        break
    url = data['links']['next']

asteroid_data

[{'id': 2415949,
  'neo_reference_id': 2415949,
  'name': '415949 (2001 XY10)',
  'absolute_magnitude_h': 19.37,
  'estimated_diameter_min': 355.267088298,
  'estimated_diameter_max': 794.4013596028,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 15.8905264223,
  'astronomical': 0.3372535274,
  'miss_distance_km': 50452409.349026635,
  'miss_distance_lunar': 131.1916221586,
  'orbiting_body': 'Earth'},
 {'id': 3160747,
  'neo_reference_id': 3160747,
  'name': '(2003 SR84)',
  'absolute_magnitude_h': 26.0,
  'estimated_diameter_min': 16.7708462163,
  'estimated_diameter_max': 37.5007521798,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 10.7191818981,
  'astronomical': 0.1323425924,
  'miss_distance_km': 19798169.933318187,
  'miss_distance_lunar': 51.4812684436,
  'orbiting_body': 'Earth'},
 {'id': 3309828,
  'neo_reference_id': 3309828,
  'name': '(2005 YQ96)',
  'absolute_magnitude_h': 20.62,
  'estimated_diameter_min': 199.78136523,
  'estimated_diameter_max': 446.7247132921,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 15.6702817644,
  'astronomical': 0.1670126223,
  'miss_distance_km': 24984732.5591945,
  'miss_distance_lunar': 64.9679100747,
  'orbiting_body': 'Earth'},
 {'id': 3457842,
  'neo_reference_id': 3457842,
  'name': '(2009 HC21)',
  'absolute_magnitude_h': 22.1,
  'estimated_diameter_min': 101.054341542,
  'estimated_diameter_max': 225.9643771094,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 6.0808661718,
  'astronomical': 0.4920511029,
  'miss_distance_km': 73609796.92499082,
  'miss_distance_lunar': 191.4078790281,
  'orbiting_body': 'Earth'},
 {'id': 3553062,
  'neo_reference_id': 3553062,
  'name': '(2010 XA11)',
  'absolute_magnitude_h': 26.1,
  'estimated_diameter_min': 16.0160337979,
  'estimated_diameter_max': 35.8129403019,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 8.7413828775,
  'astronomical': 0.2358022486,
  'miss_distance_km': 35275514.131770484,
  'miss_distance_lunar': 91.7270747054,
  'orbiting_body': 'Earth'},
 {'id': 3591616,
  'neo_reference_id': 3591616,
  'name': '(2011 YP10)',
  'absolute_magnitude_h': 23.94,
  'estimated_diameter_min': 43.3066885476,
  'estimated_diameter_max': 96.8366994728,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 5.8070023218,
  'astronomical': 0.0704899554,
  'miss_distance_km': 10545147.184234997,
  'miss_distance_lunar': 27.4205926506,
  'orbiting_body': 'Earth'},
 {'id': 3608936,
  'neo_reference_id': 3608936,
  'name': '(2012 SD22)',
  'absolute_magnitude_h': 20.05,
  'estimated_diameter_min': 259.7496533301,
  'estimated_diameter_max': 580.817881978,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 11.0227943004,
  'astronomical': 0.1644228854,
  'miss_distance_km': 24597313.4350941,
  'miss_distance_lunar': 63.9605024206,
  'orbiting_body': 'Earth'},
 {'id': 3795154,
  'neo_reference_id': 3795154,
  'name': '(2017 YD8)',
  'absolute_magnitude_h': 21.87,
  'estimated_diameter_min': 112.3453176718,
  'estimated_diameter_max': 251.2117672679,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 18.9936426332,
  'astronomical': 0.2012574006,
  'miss_distance_km': 30107678.45149672,
  'miss_distance_lunar': 78.2891288334,
  'orbiting_body': 'Earth'},
 {'id': 3842680,
  'neo_reference_id': 3842680,
  'name': '(2019 KK5)',
  'absolute_magnitude_h': 22.79,
  'estimated_diameter_min': 73.545308935,
  'estimated_diameter_max': 164.452310205,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 20.8331302779,
  'astronomical': 0.0260972745,
  'miss_distance_km': 3904096.678005315,
  'miss_distance_lunar': 10.1518397805,
  'orbiting_body': 'Earth'},
 {'id': 2613286,
  'neo_reference_id': 2613286,
  'name': '613286 (2005 YQ96)',
  'absolute_magnitude_h': 20.63,
  'estimated_diameter_min': 198.8634532359,
  'estimated_diameter_max': 444.6721996757,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 15.6702896005,
  'astronomical': 0.16701304,
  'miss_distance_km': 24984795.0462248,
  'miss_distance_lunar': 64.96807256,
  'orbiting_body': 'Earth'},
 {'id': 2669051,
  'neo_reference_id': 2669051,
  'name': '669051 (2012 SD22)',
  'absolute_magnitude_h': 20.08,
  'estimated_diameter_min': 256.1857544793,
  'estimated_diameter_max': 572.8487618827,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-02',
  'relative_velocity_km_per_sec': 11.0227939149,
  'astronomical': 0.1644228604,
  'miss_distance_km': 24597309.695147347,
  'miss_distance_lunar': 63.9604926956,
  'orbiting_body': 'Earth'},
 {'id': 3724393,
  'neo_reference_id': 3724393,
  'name': '(2015 OD22)',
  'absolute_magnitude_h': 21.21,
  'estimated_diameter_min': 152.249185036,
  'estimated_diameter_max': 340.4395272595,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_km_per_sec': 25.3931645932,
  'astronomical': 0.4372881787,
  'miss_distance_km': 65417380.10969937,
  'miss_distance_lunar': 170.1051015143,
  'orbiting_body': 'Earth'},
 {'id': 3797695,
  'neo_reference_id': 3797695,
  'name': '(2018 BA)',
  'absolute_magnitude_h': 25.0,
  'estimated_diameter_min': 26.58,
  'estimated_diameter_max': 59.4346868419,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_km_per_sec': 16.7051869184,
  'astronomical': 0.3961064439,
  'miss_distance_km': 59256680.30071449,
  'miss_distance_lunar': 154.0854066771,
  'orbiting_body': 'Earth'},
 {'id': 3986699,
  'neo_reference_id': 3986699,
  'name': '(2020 BC)',
  'absolute_magnitude_h': 26.2,
  'estimated_diameter_min': 15.2951935344,
  'estimated_diameter_max': 34.201092472,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-01',
  'relative_velocity_km_per_sec': 8.3141771772,
  'astronomical': 0.1675870266,
  'miss_distance_km': 25070662.218993343,
  'miss_distance_lunar': 65.1913533474,
  'orbiting_body': 'Earth'},
 {'id': 3541505,
  'neo_reference_id': 3541505,
  'name': '(2010 PJ)',
  'absolute_magnitude_h': 22.14,
  'estimated_diameter_min': 99.2098919421,
  'estimated_diameter_max': 221.8400624229,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-04',
  'relative_velocity_km_per_sec': 18.4122352237,
  'astronomical': 0.325882928,
  'miss_distance_km': 48751391.89816336,
  'miss_distance_lunar': 126.768458992,
  'orbiting_body': 'Earth'},
 {'id': 3759758,
  'neo_reference_id': 3759758,
  'name': '(2016 SU2)',
  'absolute_magnitude_h': 27.6,
  'estimated_diameter_min': 8.0270316728,
  'estimated_diameter_max': 17.948988478,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-04',
  'relative_velocity_km_per_sec': 17.1238660723,
  'astronomical': 0.1648175282,
  'miss_distance_km': 24656351.157384936,
  'miss_distance_lunar': 64.1140184698,
  'orbiting_body': 'Earth'},
 {'id': 3154493,
  'neo_reference_id': 3154493,
  'name': '(2003 JV14)',
  'absolute_magnitude_h': 21.39,
  'estimated_diameter_min': 140.1376971662,
  'estimated_diameter_max': 313.3574170739,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 13.6603242742,
  'astronomical': 0.2621610014,
  'miss_distance_km': 39218727.406507015,
  'miss_distance_lunar': 101.9806295446,
  'orbiting_body': 'Earth'},
 {'id': 3591759,
  'neo_reference_id': 3591759,
  'name': '(2011 YE40)',
  'absolute_magnitude_h': 25.2,
  'estimated_diameter_min': 24.2412481101,
  'estimated_diameter_max': 54.2050786336,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 13.0832838643,
  'astronomical': 0.1185645923,
  'miss_distance_km': 17737010.465498403,
  'miss_distance_lunar': 46.1216264047,
  'orbiting_body': 'Earth'},
 {'id': 3595775,
  'neo_reference_id': 3595775,
  'name': '(2012 AB11)',
  'absolute_magnitude_h': 22.32,
  'estimated_diameter_min': 91.3177025518,
  'estimated_diameter_max': 204.1925904549,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 18.3613912555,
  'astronomical': 0.2870697327,
  'miss_distance_km': 42945020.55338935,
  'miss_distance_lunar': 111.6701260203,
  'orbiting_body': 'Earth'},
 {'id': 3605578,
  'neo_reference_id': 3605578,
  'name': '(2012 LJ2)',
  'absolute_magnitude_h': 21.7,
  'estimated_diameter_min': 121.4940407996,
  'estimated_diameter_max': 271.6689340891,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 17.3904977402,
  'astronomical': 0.4856779711,
  'miss_distance_km': 72656389.98248155,
  'miss_distance_lunar': 188.9287307579,
  'orbiting_body': 'Earth'},
 {'id': 3645001,
  'neo_reference_id': 3645001,
  'name': '(2013 NT11)',
  'absolute_magnitude_h': 19.49,
  'estimated_diameter_min': 336.1669211578,
  'estimated_diameter_max': 751.6920874957,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 37.852109203,
  'astronomical': 0.3878716833,
  'miss_distance_km': 58024777.65499457,
  'miss_distance_lunar': 150.8820848037,
  'orbiting_body': 'Earth'},
 {'id': 3751529,
  'neo_reference_id': 3751529,
  'name': '(2016 GZ215)',
  'absolute_magnitude_h': 21.08,
  'estimated_diameter_min': 161.6422833399,
  'estimated_diameter_max': 361.4431335863,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 3.7257304746,
  'astronomical': 0.3169592421,
  'miss_distance_km': 47416427.49497433,
  'miss_distance_lunar': 123.2971451769,
  'orbiting_body': 'Earth'},
 {'id': 3787600,
  'neo_reference_id': 3787600,
  'name': '(2017 UJ2)',
  'absolute_magnitude_h': 30.9,
  'estimated_diameter_min': 1.7561231848,
  'estimated_diameter_max': 3.9268108181,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 5.6646429678,
  'astronomical': 0.2789034507,
  'miss_distance_km': 41723362.16037001,
  'miss_distance_lunar': 108.4934423223,
  'orbiting_body': 'Earth'},
 {'id': 3789479,
  'neo_reference_id': 3789479,
  'name': '(2017 WQ1)',
  'absolute_magnitude_h': 24.98,
  'estimated_diameter_min': 26.8259417119,
  'estimated_diameter_max': 59.9846292283,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 21.6521650376,
  'astronomical': 0.3928589898,
  'miss_distance_km': 58770868.08443172,
  'miss_distance_lunar': 152.8221470322,
  'orbiting_body': 'Earth'},
 {'id': 3837605,
  'neo_reference_id': 3837605,
  'name': '(2019 AE3)',
  'absolute_magnitude_h': 27.4,
  'estimated_diameter_min': 8.801465209,
  'estimated_diameter_max': 19.6806745089,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 8.5121919111,
  'astronomical': 0.219831404,
  'miss_distance_km': 32886309.79750948,
  'miss_distance_lunar': 85.514416156,
  'orbiting_body': 'Earth'},
 {'id': 3986746,
  'neo_reference_id': 3986746,
  'name': '(2020 BG1)',
  'absolute_magnitude_h': 22.08,
  'estimated_diameter_min': 101.9893858518,
  'estimated_diameter_max': 228.0551997482,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 8.5169042448,
  'astronomical': 0.4392947647,
  'miss_distance_km': 65717561.10127119,
  'miss_distance_lunar': 170.8856634683,
  'orbiting_body': 'Earth'},
 {'id': 2668499,
  'neo_reference_id': 2668499,
  'name': '668499 (2012 AB11)',
  'absolute_magnitude_h': 22.32,
  'estimated_diameter_min': 91.3177025518,
  'estimated_diameter_max': 204.1925904549,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-03',
  'relative_velocity_km_per_sec': 18.3613912419,
  'astronomical': 0.2870697328,
  'miss_distance_km': 42945020.56834914,
  'miss_distance_lunar': 111.6701260592,
  'orbiting_body': 'Earth'},
 {'id': 2304640,
  'neo_reference_id': 2304640,
  'name': '304640 (2006 WW1)',
  'absolute_magnitude_h': 19.17,
  'estimated_diameter_min': 389.5426161261,
  'estimated_diameter_max': 871.043769791,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 23.0326073542,
  'astronomical': 0.3042250642,
  'miss_distance_km': 45511421.604933254,
  'miss_distance_lunar': 118.3435499738,
  'orbiting_body': 'Earth'},
 {'id': 3102756,
  'neo_reference_id': 3102756,
  'name': '(2002 AO11)',
  'absolute_magnitude_h': 23.05,
  'estimated_diameter_min': 65.2461629789,
  'estimated_diameter_max': 145.8948556919,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 18.4313859429,
  'astronomical': 0.4011389088,
  'miss_distance_km': 60009526.330604255,
  'miss_distance_lunar': 156.0430355232,
  'orbiting_body': 'Earth'},
 {'id': 3623521,
  'neo_reference_id': 3623521,
  'name': '(2013 AK20)',
  'absolute_magnitude_h': 23.19,
  'estimated_diameter_min': 61.1723235067,
  'estimated_diameter_max': 136.7854737026,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 9.2913935384,
  'astronomical': 0.2658726974,
  'miss_distance_km': 39773989.22219454,
  'miss_distance_lunar': 103.4244792886,
  'orbiting_body': 'Earth'},
 {'id': 3630638,
  'neo_reference_id': 3630638,
  'name': '(2013 EU9)',
  'absolute_magnitude_h': 21.66,
  'estimated_diameter_min': 123.7527836584,
  'estimated_diameter_max': 276.719636665,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 6.4568616725,
  'astronomical': 0.4595500589,
  'miss_distance_km': 68747709.96981454,
  'miss_distance_lunar': 178.7649729121,
  'orbiting_body': 'Earth'},
 {'id': 3752775,
  'neo_reference_id': 3752775,
  'name': '(2016 JX5)',
  'absolute_magnitude_h': 26.9,
  'estimated_diameter_min': 11.0803882126,
  'estimated_diameter_max': 24.7765012606,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 13.1693944854,
  'astronomical': 0.219641036,
  'miss_distance_km': 32857831.15019332,
  'miss_distance_lunar': 85.440363004,
  'orbiting_body': 'Earth'},
 {'id': 3780672,
  'neo_reference_id': 3780672,
  'name': '(2017 PM26)',
  'absolute_magnitude_h': 21.28,
  'estimated_diameter_min': 147.4195145042,
  'estimated_diameter_max': 329.6400556414,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 18.612928453,
  'astronomical': 0.2157438397,
  'miss_distance_km': 32274818.88474144,
  'miss_distance_lunar': 83.9243536433,
  'orbiting_body': 'Earth'},
 {'id': 3794988,
  'neo_reference_id': 3794988,
  'name': '(2017 YZ1)',
  'absolute_magnitude_h': 20.43,
  'estimated_diameter_min': 218.0494404829,
  'estimated_diameter_max': 487.5733713755,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 12.2272943072,
  'astronomical': 0.4823054753,
  'miss_distance_km': 72151871.79421762,
  'miss_distance_lunar': 187.6168298917,
  'orbiting_body': 'Earth'},
 {'id': 2591179,
  'neo_reference_id': 2591179,
  'name': '591179 (2013 EU9)',
  'absolute_magnitude_h': 21.66,
  'estimated_diameter_min': 123.7527836584,
  'estimated_diameter_max': 276.719636665,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-06',
  'relative_velocity_km_per_sec': 6.4568624469,
  'astronomical': 0.4595501104,
  'miss_distance_km': 68747717.67410485,
  'miss_distance_lunar': 178.7649929456,
  'orbiting_body': 'Earth'},
 {'id': 3387092,
  'neo_reference_id': 3387092,
  'name': '(2007 SG11)',
  'absolute_magnitude_h': 22.68,
  'estimated_diameter_min': 77.3668609982,
  'estimated_diameter_max': 172.9975603978,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_km_per_sec': 5.8695959378,
  'astronomical': 0.279217138,
  'miss_distance_km': 41770289.11229606,
  'miss_distance_lunar': 108.615466682,
  'orbiting_body': 'Earth'},
 {'id': 3655366,
  'neo_reference_id': 3655366,
  'name': '(2013 YD)',
  'absolute_magnitude_h': 23.6,
  'estimated_diameter_min': 50.6471458835,
  'estimated_diameter_max': 113.2504610618,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_km_per_sec': 26.4969302496,
  'astronomical': 0.4134715606,
  'miss_distance_km': 61854464.77133592,
  'miss_distance_lunar': 160.8404370734,
  'orbiting_body': 'Earth'},
 {'id': 3759280,
  'neo_reference_id': 3759280,
  'name': '(2016 RW19)',
  'absolute_magnitude_h': 20.97,
  'estimated_diameter_min': 170.0415192713,
  'estimated_diameter_max': 380.2243960879,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_km_per_sec': 15.4546352377,
  'astronomical': 0.3310608323,
  'miss_distance_km': 49525995.352507204,
  'miss_distance_lunar': 128.7826637647,
  'orbiting_body': 'Earth'},
 {'id': 3795150,
  'neo_reference_id': 3795150,
  'name': '(2017 YA8)',
  'absolute_magnitude_h': 22.33,
  'estimated_diameter_min': 90.8981358201,
  'estimated_diameter_max': 203.2544107219,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_km_per_sec': 20.6375976951,
  'astronomical': 0.47281464,
  'miss_distance_km': 70732063.0488168,
  'miss_distance_lunar': 183.92489496,
  'orbiting_body': 'Earth'},
 {'id': 3989198,
  'neo_reference_id': 3989198,
  'name': '(2020 BT8)',
  'absolute_magnitude_h': 22.66,
  'estimated_diameter_min': 78.0827277491,
  'estimated_diameter_max': 174.5982871157,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-05',
  'relative_velocity_km_per_sec': 9.113812766,
  'astronomical': 0.4020460517,
  'miss_distance_km': 60145232.97622988,
  'miss_distance_lunar': 156.3959141113,
  'orbiting_body': 'Earth'},
 {'id': 2199003,
  'neo_reference_id': 2199003,
  'name': '199003 (2005 WJ56)',
  'absolute_magnitude_h': 18.16,
  'estimated_diameter_min': 620.2331529543,
  'estimated_diameter_max': 1386.8834919048,
  'is_potentially_hazardous_asteroid': True,
  'close_approach_date': '2024-01-07',
  'relative_velocity_km_per_sec': 15.2908365812,
  'astronomical': 0.1995345465,
  'miss_distance_km': 29849943.147815954,
  'miss_distance_lunar': 77.6189385885,
  'orbiting_body': 'Earth'},
 {'id': 3398095,
  'neo_reference_id': 3398095,
  'name': '(2007 YZ)',
  'absolute_magnitude_h': 19.53,
  'estimated_diameter_min': 330.0311833581,
  'estimated_diameter_max': 737.9721606833,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-07',
  'relative_velocity_km_per_sec': 17.5905780686,
  'astronomical': 0.1917666817,
  'miss_distance_km': 28687887.11928798,
  'miss_distance_lunar': 74.5972391813,
  'orbiting_body': 'Earth'},
 {'id': 3520662,
  'neo_reference_id': 3520662,
  'name': '(2010 JR34)',
  'absolute_magnitude_h': 27.7,
  'estimated_diameter_min': 7.6657557353,
  'estimated_diameter_max': 17.1411509231,
  'is_potentially_hazardous_asteroid': False,
  'close_approach_date': '2024-01-07',

In [97]:
len(asteroid_data)

1000

In [30]:
cleaned_data = []

In [98]:
from datetime import datetime

cleaned_data = []

for date, asteroids in data["near_earth_objects"].items():

    for asteroid in asteroids:

        approach = asteroid["close_approach_data"][0]

        record = {

            "id": int(asteroid.get("id", 0)),
            "neo_reference_id": int(asteroid.get("neo_reference_id", 0)),
            "name": asteroid.get("name", ""),
            "absolute_magnitude_h": float(asteroid.get("absolute_magnitude_h", 0)),

            "estimated_diameter_min_km":
                float(
                    asteroid.get("estimated_diameter", {})
                            .get("kilometers", {})
                            .get("estimated_diameter_min", 0)
                ),

            "estimated_diameter_max_km":
                float(
                    asteroid.get("estimated_diameter", {})
                            .get("kilometers", {})
                            .get("estimated_diameter_max", 0)
                ),

            "is_potentially_hazardous_asteroid":
                asteroid.get("is_potentially_hazardous_asteroid", False),

            "close_approach_date":
                datetime.strptime(
                    approach.get("close_approach_date"),
                    "%Y-%m-%d"
                ).date(),

            "relative_velocity_kmph":
                float(
                    approach.get("relative_velocity", {})
                            .get("kilometers_per_hour", 0)
                ),

            "astronomical":
                float(
                    approach.get("miss_distance", {})
                            .get("astronomical", 0)
                ),

            "miss_distance_km":
                float(
                    approach.get("miss_distance", {})
                            .get("kilometers", 0)
                ),

            "miss_distance_lunar":
                float(
                    approach.get("miss_distance", {})
                            .get("lunar", 0)
                ),

            "orbiting_body":
                approach.get("orbiting_body", "")
        }

        cleaned_data.append(record)

In [99]:
print(len(cleaned_data))

35

In [100]:
from pprint import pprint

pprint(cleaned_data[0])

{'absolute_magnitude_h': 24.6,
 'astronomical': 0.1903395014,
 'close_approach_date': datetime.date(2024, 5, 18),
 'estimated_diameter_max_km': 0.0714562102,
 'estimated_diameter_min_km': 0.0319561887,
 'id': 3261401,
 'is_potentially_hazardous_asteroid': False,
 'miss_distance_km': 28474383.98630202,
 'miss_distance_lunar': 74.0420660446,
 'name': '(2004 VZ)',
 'neo_reference_id': 3261401,
 'orbiting_body': 'Earth',
 'relative_velocity_kmph': 39203.2909795824}

In [101]:
print(type(cleaned_data[0]["id"]))
print(type(cleaned_data[0]["absolute_magnitude_h"]))
print(type(cleaned_data[0]["close_approach_date"]))
print(type(cleaned_data[0]["is_potentially_hazardous_asteroid"]))

<class 'int'>
<class 'float'>
<class 'datetime.date'>
<class 'bool'>

In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\shaguftha\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [59]:
import mysql.connector

In [60]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root"
)

cursor = conn.cursor()

print("Connected Successfully!")

Connected Successfully!

In [61]:
cursor.execute("""
CREATE DATABASE IF NOT EXISTS nasa_asteroids;
""")

print("Database Created")

Database Created

In [62]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="nasa_asteroids"
)

cursor = conn.cursor()

print("Connected to Database")

Connected to Database

In [63]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS asteroids (

    id BIGINT,
    name VARCHAR(200),
    absolute_magnitude_h FLOAT,
    estimated_diameter_min_km FLOAT,
    estimated_diameter_max_km FLOAT,
    is_potentially_hazardous_asteroid BOOLEAN,

    PRIMARY KEY(id)

);
""")

print("Asteroids Table Created")

Asteroids Table Created

In [64]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS close_approach (

    approach_id INT AUTO_INCREMENT PRIMARY KEY,

    neo_reference_id BIGINT,

    close_approach_date DATE,

    relative_velocity_kmph FLOAT,

    astronomical FLOAT,

    miss_distance_km FLOAT,

    miss_distance_lunar FLOAT,

    orbiting_body VARCHAR(30),

    FOREIGN KEY (neo_reference_id)
    REFERENCES asteroids(id)

);
""")

print("Close Approach Table Created")

Close Approach Table Created

In [65]:
conn.commit()

In [66]:
cursor.execute("SHOW TABLES")

for table in cursor:
    print(table)

('asteroids',)
('close_approach',)

In [67]:
insert_asteroid = """
INSERT IGNORE INTO asteroids
(id,
name,
absolute_magnitude_h,
estimated_diameter_min_km,
estimated_diameter_max_km,
is_potentially_hazardous_asteroid)

VALUES (%s,%s,%s,%s,%s,%s)
"""

In [68]:
for asteroid in cleaned_data:

    values = (
        asteroid["id"],
        asteroid["name"],
        asteroid["absolute_magnitude_h"],
        asteroid["estimated_diameter_min_km"],
        asteroid["estimated_diameter_max_km"],
        asteroid["is_potentially_hazardous_asteroid"]
    )

    cursor.execute(insert_asteroid, values)

conn.commit()

print("Asteroids inserted successfully.")

Asteroids inserted successfully.

In [69]:
insert_close = """
INSERT INTO close_approach
(
neo_reference_id,
close_approach_date,
relative_velocity_kmph,
astronomical,
miss_distance_km,
miss_distance_lunar,
orbiting_body
)

VALUES (%s,%s,%s,%s,%s,%s,%s)
"""

In [70]:
for asteroid in cleaned_data:

    values = (
        asteroid["neo_reference_id"],
        asteroid["close_approach_date"],
        asteroid["relative_velocity_kmph"],
        asteroid["astronomical"],
        asteroid["miss_distance_km"],
        asteroid["miss_distance_lunar"],
        asteroid["orbiting_body"]
    )

    cursor.execute(insert_close, values)

conn.commit()

print("Close approach data inserted successfully.")

Close approach data inserted successfully.

In [71]:
cursor.execute("SELECT COUNT(*) FROM asteroids")
print("Asteroids:", cursor.fetchone()[0])

cursor.execute("SELECT COUNT(*) FROM close_approach")
print("Close Approaches:", cursor.fetchone()[0])

Asteroids: 35
Close Approaches: 70

In [72]:
import pandas as pd

In [73]:
def run_query(query):
    cursor.execute(query)

    rows = cursor.fetchall()

    columns = [col[0] for col in cursor.description]

    df = pd.DataFrame(rows, columns=columns)

    return df

In [74]:
df = run_query(query)

Query 1
Count how many times each asteroid has approached Earth

In [76]:
query = """
SELECT
    a.name,
    COUNT(*) AS total_approaches
FROM asteroids a
JOIN close_approach c
ON a.id = c.neo_reference_id
GROUP BY a.id, a.name
ORDER BY total_approaches DESC;
"""

run_query(query)

                  name  total_approaches
0    86667 (2000 FO10)                 2
1   381677 (2009 BJ81)                 2
2    481052 (2005 HD4)                 2
3   620097 (2016 HD19)                 2
4    679756 (2020 KP1)                 2
5          (1999 RP28)                 2
6          (2004 BT58)                 2
7            (2004 VZ)                 2
8           (2005 XN4)                 2
9           (2011 HO5)                 2
10         (2011 KY15)                 2
11           (2011 WC)                 2
12          (2012 JU4)                 2
13         (2012 VJ77)                 2
14        (2013 CN118)                 2
15        (2014 QP363)                 2
16        (2014 SD304)                 2
17          (2014 WF6)                 2
18         (2015 HF11)                 2
19         (2015 KJ19)                 2
20        (2016 AH193)                 2
21         (2016 HD19)                 2
22        (2017 FS101)                 2
23          (2017 HP3)                 2
24          (2017 JF3)                 2
25          (2017 RX2)                 2
26          (2017 TG2)                 2
27         (2017 UM52)                 2
28           (2019 GA)                 2
29          (2019 JX1)                 2
30          (2019 JZ2)                 2
31          (2019 JD6)                 2
32          (2019 YS3)                 2
33          (2020 AC1)                 2
34          (2020 KP1)                 2

2. Average velocity of each asteroid over multiple approaches

In [78]:
query = """
SELECT
    a.name,
    ROUND(AVG(c.relative_velocity_kmph),2) AS average_velocity
FROM asteroids a
JOIN close_approach c
ON a.id = c.neo_reference_id
GROUP BY a.id,a.name
ORDER BY average_velocity DESC;
"""

run_query(query)

                  name  average_velocity
0   620097 (2016 HD19)         135006.44
1          (2016 HD19)         135006.44
2         (2016 AH193)         132451.48
3           (2017 TG2)         115821.21
4           (2019 JZ2)         101119.09
5           (2005 XN4)          98837.69
6         (2013 CN118)          87547.77
7           (2019 JX1)          86791.29
8          (2015 KJ19)          83174.89
9           (2017 JF3)          82016.07
10         (2012 VJ77)          81180.17
11         (2011 KY15)          75094.84
12          (2014 WF6)          68122.24
13         (2015 HF11)          67618.98
14         (2004 BT58)          64961.58
15        (2014 QP363)          63582.86
16          (2020 KP1)          60524.11
17   679756 (2020 KP1)          60524.09
18          (2017 HP3)          56886.35
19   86667 (2000 FO10)          53153.98
20   481052 (2005 HD4)          50628.72
21         (2017 UM52)          48138.31
22          (2019 JD6)          45560.07
23          (2017 RX2)          43743.76
24           (2019 GA)          43220.07
25           (2004 VZ)          39203.29
26  381677 (2009 BJ81)          33175.47
27          (2012 JU4)          31306.09
28        (2017 FS101)          29562.77
29          (2011 HO5)          23257.37
30          (2019 YS3)          21657.25
31           (2011 WC)          20937.15
32          (2020 AC1)          18164.52
33         (1999 RP28)          18029.72
34        (2014 SD304)          16629.19

3. List Top 10 Fastest Asteroids

In [79]:
query = """
SELECT
    a.name,
    MAX(c.relative_velocity_kmph) AS max_velocity
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
GROUP BY a.id,a.name
ORDER BY max_velocity DESC
LIMIT 10;
"""

run_query(query)

                 name  max_velocity
0         (2016 HD19)      135006.0
1  620097 (2016 HD19)      135006.0
2        (2016 AH193)      132451.0
3          (2017 TG2)      115821.0
4          (2019 JZ2)      101119.0
5          (2005 XN4)       98837.7
6        (2013 CN118)       87547.8
7          (2019 JX1)       86791.3
8         (2015 KJ19)       83174.9
9          (2017 JF3)       82016.1

4. Hazardous asteroids that approached Earth more than 3 times

In [84]:
query = """
SELECT
    a.name,
    COUNT(*) AS approaches
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
WHERE a.is_potentially_hazardous_asteroid=True
GROUP BY a.id,a.name
HAVING COUNT(*)>3;
"""

run_query(query)

Empty DataFrame
Columns: [name, approaches]
Index: []

#5. Find the month with the most asteroid approaches

In [85]:
query = """
SELECT
    MONTHNAME(close_approach_date) AS month,
    COUNT(*) AS total_approaches
FROM close_approach
GROUP BY MONTH(close_approach_date),
MONTHNAME(close_approach_date)
ORDER BY total_approaches DESC
LIMIT 1;
"""

run_query(query)

  month  total_approaches
0   May                70

6. Asteroid with the fastest ever approach speed

In [86]:
query = """
SELECT
    a.name,
    c.relative_velocity_kmph
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
ORDER BY c.relative_velocity_kmph DESC
LIMIT 1;
"""

run_query(query)

                 name  relative_velocity_kmph
0  620097 (2016 HD19)                135006.0

7. Sort asteroids by maximum estimated diameter

In [87]:
query = """
SELECT
    name,
    estimated_diameter_max_km
FROM asteroids
ORDER BY estimated_diameter_max_km DESC;
"""

run_query(query)

                  name  estimated_diameter_max_km
0    86667 (2000 FO10)                   1.845190
1   381677 (2009 BJ81)                   1.264850
2   620097 (2016 HD19)                   0.990923
3          (2016 HD19)                   0.990923
4          (2015 HF11)                   0.828018
5           (2005 XN4)                   0.625230
6    481052 (2005 HD4)                   0.457130
7         (2016 AH193)                   0.409298
8         (2014 QP363)                   0.389081
9           (2012 JU4)                   0.381979
10          (2017 HP3)                   0.296510
11          (2017 TG2)                   0.275448
12          (2017 JF3)                   0.266710
13         (2004 BT58)                   0.216790
14         (1999 RP28)                   0.187949
15         (2015 KJ19)                   0.187085
16           (2011 WC)                   0.168283
17         (2012 VJ77)                   0.149293
18          (2020 KP1)                   0.142574
19   679756 (2020 KP1)                   0.140618
20           (2019 GA)                   0.113773
21        (2017 FS101)                   0.094198
22          (2011 HO5)                   0.084731
23          (2014 WF6)                   0.077990
24         (2011 KY15)                   0.077632
25           (2004 VZ)                   0.071456
26          (2019 YS3)                   0.070476
27          (2019 JD6)                   0.062812
28        (2014 SD304)                   0.057285
29        (2013 CN118)                   0.047867
30          (2017 RX2)                   0.029110
31          (2019 JZ2)                   0.025354
32          (2020 AC1)                   0.012475
33          (2019 JX1)                   0.008996
34         (2017 UM52)                   0.007380

8. Asteroid whose closest approach is getting nearer over time

In [88]:
query = """
SELECT
    a.name,
    c.close_approach_date,
    c.miss_distance_km
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
ORDER BY a.name,c.close_approach_date;
"""

run_query(query)

                  name close_approach_date  miss_distance_km
0          (1999 RP28)          2024-05-16        67240700.0
1          (1999 RP28)          2024-05-16        67240700.0
2          (2004 BT58)          2024-05-12        48321300.0
3          (2004 BT58)          2024-05-12        48321300.0
4            (2004 VZ)          2024-05-18        28474400.0
..                 ...                 ...               ...
65  620097 (2016 HD19)          2024-05-13        45083900.0
66   679756 (2020 KP1)          2024-05-15        18271800.0
67   679756 (2020 KP1)          2024-05-15        18271800.0
68   86667 (2000 FO10)          2024-05-15        29536800.0
69   86667 (2000 FO10)          2024-05-15        29536800.0

[70 rows x 3 columns]

9. Name, date and miss distance of closest approach

In [89]:
query = """
SELECT
    a.name,
    c.close_approach_date,
    c.miss_distance_km
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
WHERE c.miss_distance_km=
(
SELECT MIN(c2.miss_distance_km)
FROM close_approach c2
WHERE c2.neo_reference_id=a.id
)
ORDER BY c.miss_distance_km;
"""

run_query(query)

            name close_approach_date  miss_distance_km
0     (2014 WF6)          2024-05-14         2740300.0
1     (2014 WF6)          2024-05-14         2740300.0
2    (2015 KJ19)          2024-05-14         6042620.0
3    (2015 KJ19)          2024-05-14         6042620.0
4     (2017 HP3)          2024-05-16         8950060.0
..           ...                 ...               ...
65    (2005 XN4)          2024-05-17        72389600.0
66  (2013 CN118)          2024-05-16        72545100.0
67  (2013 CN118)          2024-05-16        72545100.0
68    (2017 RX2)          2024-05-13        74665800.0
69    (2017 RX2)          2024-05-13        74665800.0

[70 rows x 3 columns]

10. Velocity greater than 50,000 km/h

In [90]:
query = """
SELECT
    MONTHNAME(close_approach_date) AS Month,
    COUNT(*) AS Total_Approaches
FROM close_approach
GROUP BY MONTH(close_approach_date),
MONTHNAME(close_approach_date)
ORDER BY MONTH(close_approach_date);
"""

run_query(query)

  Month  Total_Approaches
0   May                70

12. Asteroid with highest brightness

In [91]:
query = """
SELECT
    name,
    absolute_magnitude_h
FROM asteroids
ORDER BY absolute_magnitude_h ASC
LIMIT 1;
"""

run_query(query)

                name  absolute_magnitude_h
0  86667 (2000 FO10)                 17.54

13. Hazardous vs Non-Hazardous Asteroids

In [92]:
query = """
SELECT
CASE
WHEN is_potentially_hazardous_asteroid=True
THEN 'Hazardous'
ELSE 'Non-Hazardous'
END AS Category,
COUNT(*) AS Total
FROM asteroids
GROUP BY is_potentially_hazardous_asteroid;
"""

run_query(query)

        Category  Total
0  Non-Hazardous     31
1      Hazardous      4

14. Passed closer than the Moon (<1 LD)

In [93]:
query = """
SELECT
    a.name,
    c.close_approach_date,
    c.miss_distance_lunar
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
WHERE c.miss_distance_lunar<1
ORDER BY c.miss_distance_lunar;
"""

run_query(query)

Empty DataFrame
Columns: [name, close_approach_date, miss_distance_lunar]
Index: []

15. Came within 0.05 AU

In [102]:
query = """
SELECT
    a.name,
    c.close_approach_date,
    c.astronomical
FROM asteroids a
JOIN close_approach c
ON a.id=c.neo_reference_id
WHERE c.astronomical<0.05
ORDER BY c.astronomical;
"""

run_query(query)

          name close_approach_date  astronomical
0   (2014 WF6)          2024-05-14      0.018318
1   (2014 WF6)          2024-05-14      0.018318
2  (2015 KJ19)          2024-05-14      0.040392
3  (2015 KJ19)          2024-05-14      0.040392

In [115]:
!streamlit run app.py

^C